export const TOGGLE_DARK_THEME = "TOGGLE_DARK_THEME";
export const HANDLE_DRAWER_STATE = "HANDLE_DRAWER_STATE";
export const HANDLE_DIALOG_STATE = "HANDLE_DIALOG_STATE";

export const USER_LOADING = "USER_LOADING";
export const POST_LOADING = "POST_LOADING";
