// App
export const TOGGLE_DARK_THEME = "TOGGLE_DARK_THEME";
export const HANDLE_DRAWER_STATE = "HANDLE_DRAWER_STATE";
export const HANDLE_DIALOG_STATE = "HANDLE_DIALOG_STATE";
// Loading - request
export const REQUEST_LOADING = "REQUEST_LOADING";
// Loading - auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
// Signin
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
//sign out
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
// Signup
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
// Errors
export const SNACKBAR_TOGGLE = "SNACKBAR_TOGGLE";
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
// Links
export const ADD_LINK = "ADD_LINK";
export const GET_USER_LINKS = "GET_USER_LINKS";
export const SET_SINGLE_LINKS = "SET_SINGLE_LINKS";
export const SET_SINGLE_LINK_DETAILS = "SET_SINGLE_LINK_DETAILS";
export const CLEAR_SINGLE_LINKS = "CLEAR_SINGLE_LINKS";
export const CLEAR_USER_LINKS = "CLEAR_USER_LINKS";
export const LOAD_LINK = "LOAD_LINK";
export const LOAD_LINK_FAIL = "LOAD_LINK_FAIL";
export const SET_EDIT_LINK = "SET_EDIT_LINK";
export const CLEAR_EDIT_LINK = "CLEAR_EDIT_LINK";
export const SET_SENTLINK_DETAILS = "SET_SENTLINK_DETAILS";
export const SET_LINK_SENT_STATUS = "SET_LINK_SENT_STATUS";
// Clipboard
export const CLIPBOARD_STATE = "CLIPBOARD_STATE";
// Search
export const SET_SEARCH_KEYWORD = "SET_SEARCH_KEYWORD";
export const SET_GLOBAL_SEARCH_RESULT = "SET_GLOBAL_SEARCH_RESULT";
export const SEARCH_LINK_LOAD = "SEARCH_LINK_LOAD";
